general.import = [ "~/.config/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

normal = { family = "Hack", style = "Regular" }
bold = { family = "Hack", style = "Bold" }
italic = { family = "Hack", style = "Italic" }
bold_italic = { family = "Hack", style = "Bold Italic" }
