name = "system-tools"
name_pretty = "System Tools" 
icon = " "

[[entries]]
text = "Set System Theme"
icon = ""
actions = { "set-system-theme" = "bash ~/.config/elephant/menus/set-system-theme.sh" }

[[entries]]
text = "Set System Font"
icon = ""
actions = { "set-system-font" = "bash ~/.config/elephant/menus/set-system-font.sh" }

[[entries]]
text = "Set Shell"
icon = ""
actions = { "set-shell" = "bash ~/.config/elephant/menus/set-shell.sh" }

[[entries]]
text = "Set Brightness"
icon = ""
actions = { "set-brightness" = "bash ~/.config/elephant/menus/brightness.sh" }

[[entries]]
text = "System Refresh"
icon = ""
actions = { "system-refresh" = "systemd-run --user --setenv=PATH='$PATH' bash -lc \"~/.local/bin/system-refresh && notify-send 'System Refreshed!'\"" }

[[entries]]
text = "Install Package"
icon = "󰣇"
actions = { "install-package" = "ghostty --class=TUI.float -e ~/.local/bin/dotfiles install-package" }

[[entries]]
text = "Remove Package"
icon = "󰭌"
actions = { "remove-package" = "ghostty --class=TUI.float -e ~/.local/bin/dotfiles remove-package" }

[[entries]]
text = "Update System"
icon = "󰚰"
actions = { "update-system" = "ghostty --class=TUI.float -e ~/.local/bin/system-perform-update" }

[[entries]]
text = "Toggle Nightlight"
icon = ""
actions = { "toggle-nightlight" = "bash ~/.local/bin/run-notify system-theme nightlight" }
