[package]
name = "syscli"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[dependencies.clap]
version = "4.5.52"
features = ["suggestions", "color", "wrap_help", "cargo", "derive"]
